// Representative country list — covers primary Intralox markets.
// Full 150-country list from the live form should replace this for production.
export const COUNTRY_OPTIONS = [
  'United States',
  'Canada',
  'Mexico',
  'Argentina',
  'Brazil',
  'Chile',
  'Colombia',
  'Peru',
  'Austria',
  'Belgium',
  'Czech Republic',
  'Denmark',
  'Finland',
  'France',
  'Germany',
  'Hungary',
  'Ireland',
  'Italy',
  'Netherlands',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Spain',
  'Sweden',
  'Switzerland',
  'Turkey',
  'United Kingdom',
  'Australia',
  'China',
  'India',
  'Indonesia',
  'Japan',
  'Malaysia',
  'New Zealand',
  'Philippines',
  'Singapore',
  'South Korea',
  'Taiwan',
  'Thailand',
  'Vietnam',
  'Egypt',
  'Israel',
  'Morocco',
  'Saudi Arabia',
  'South Africa',
  'United Arab Emirates',
  'Other',
]
